image: fhyx/golang:stab

stages:
  - lint
  - test
  - release

variables:
  DEPLOY_HOST: earth
  DEPLOY_USER: sa
  CGO_ENABLED: '0'
  GO111MODULE: 'on'
  GOPROXY: https://goproxy.io,direct
  GOPRIVATE: daxv.cn,hyyl.xyz
  NAME: ovpntend
  ROOF: github.com/liut/ovpntend
  OVPN_EASYRSA_PKI: /build/test

before_script:
  # GO ENV
  - export GOPATH=${CI_PROJECT_DIR}/vendor/go
  - which go
  - go version
  - go env

  # Builds
  - export DATE=$(date '+%Y%m%d')
  - export TAG="${DATE}-${CI_JOB_ID}"
  - export LDFLAGS="-X ${ROOF}/cmd.built=${DATE} -X ${ROOF}/cmd.name=${NAME} -X ${ROOF}/cmd.version=${TAG} -X ${ROOF}/settings.version=${TAG}"
  - echo "${TAG}"

  # Deploy SSH
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - (echo "$SSH_PRIVATE_KEY") > ~/.ssh/id_ecdsa
  - chmod 0600 ~/.ssh/id_ecdsa
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - echo -e "Host ${DEPLOY_HOST:-earth}\n\tPort ${DEPLOY_PORT:-22}\n\tUser ${DEPLOY_USER:-sa}\n\n" >> ~/.ssh/config

  - git config --global url."git@git.hyyl.xyz:".insteadOf "https://git.hyyl.xyz/"

test-lint:
  stage: lint
  services: []
  script:
    - go vet -all ./cmd/... ./pkg/...

test-status:
  stage: test
  script:
    - go test -v -cover ./pkg/status

release:
  stage: release
  services: []
  script:
    - mkdir -p dist/linux_amd64
    - GOOS=linux GOARCH=amd64 go build -ldflags "${LDFLAGS} -s -w" -o dist/linux_amd64/${NAME} ${CI_PROJECT_DIR}
    - ls dist/linux_amd64 | xargs tar -cvJf ${NAME}-linux-amd64-${TAG}.tar.xz -C dist/linux_amd64
    - scp *-linux-amd64-*.tar.?z "${DEPLOY_HOST}:/var/opt/gopkg/"
  artifacts:
    name: "${CI_JOB_STAGE}_${CI_JOB_ID}"
    paths:
     - dist/
  only:
    - master@platform/ovpntend
  when: on_success

