image: fhyx/golang:1.13.10

stages:
  - deps
  - lint
  - test

variables:
  OVPN_EASYRSA_PKI: /build/test

before_script:
  # GO ENV
  - export GOPATH=${CI_PROJECT_DIR}/vendor/go
  - export CGO_ENABLED=0
  - export GO111MODULE=on
  - export GOPROXY=https://goproxy.cn,direct
  - export GOPRIVATE=fhyx.tech
  - which go
  - go version
  - go env

  # Builds
  - export NAME=ovpntend
  - export ROOF=fhyx.tech/platform/ovpntend
  - export DATE=$(date '+%Y%m%d')
  - export TAG="${DATE}-${CI_JOB_ID}"
  - echo "${TAG}"

  # Deploy SSH
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - (echo "$SSH_PRIVATE_KEY") > ~/.ssh/id_ecdsa
  - chmod 0600 ~/.ssh/id_ecdsa
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

.modcache: &modcache
  key: modcache
  paths:
    - vendor/go/pkg/mod

deps:
  stage: deps
  script: go mod download
  cache: *modcache

test-lint:
  stage: lint
  services: []
  script:
    - go vet -all ./cmd/... ./pkg/...
  cache:
    <<: *modcache
    policy: pull

test-status:
  stage: test
  script:
    - go test -v -cover ./pkg/status
  cache:
    <<: *modcache
    policy: pull

